superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]


urlpatterns += staticfiles_urlpatterns()

superheroes/urls.py
from django.urls import path
from . import views

app_name = 'superheroes'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hero_id>/', views.detail, name = 'detail'),
    path('create/', views.create, name = 'create'),
    path('edit/<int:hero_id>/', views.edit, name = 'edit'),
    path('delete/<int:hero_id>/', views.delete, name = 'delete')
]

superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero
# Create your views here.

def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk = hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name = name, alter_ego = alter_ego, primary_ability = primary, secondary_ability = secondary, catch_phrase = catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    single_hero = Superhero.objects.get(pk = hero_id)
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        single_hero.name = name
        single_hero.alter_ego = alter_ego
        single_hero.primary_ability = primary
        single_hero.secondary_ability = secondary
        single_hero.catch_phrase = catchphrase
        single_hero.save()
        return HttpResponseRedirect(reverse('superheroes:detail', kwargs = {"hero_id": single_hero.id}))
    else:
        context = {
            'single_hero': single_hero
        }
        return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    delete_hero = Superhero.objects.get(pk = hero_id)
    delete_hero.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'superheroes/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>

    <header>
        <div class = "row">
            <div class = "col-md-6">
                <h1>League of Superheroes</h1>
            </div>
            <div class = "col-md-6">
                <a href = "{% url 'superheroes:index' %}" class="btn btn-success" >Home</a>
                <a href="{% url 'superheroes:create' %}" class = "btn btn-danger">Create new hero!</a>
            </div>
        </div>
    </header>

    <form action="{% url 'superheroes:create' %}" method = "post">
        {% csrf_token %}
        Name: <input type="text" name = "name" id = "name"><br>
        Alter Ego: <input type="text" name = "alter_ego" id = "alter_ego"><br>
        Primary Ability: <input type="text" name = "primary" id = "primary"><br>
        Secondary Ability: <input type="text" name = "secondary" id = "secondary"><br>
        Catchphrase : <input type="text" name = "catchphrase" id = "catchphrase"><br>
        <input type="submit" value = "Add!">
    </form>
</body>
</html>

superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details of Superhero</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'superheroes/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>

    <header>
        <div class = "row">
            <div class = "col-md-6">
                <h1>League of Superheroes</h1>
            </div>
            <div class = "col-md-6">
                <a href = "{% url 'superheroes:index' %}" class="btn btn-success" >Home</a>
                <a href="{% url 'superheroes:create' %}" class = "btn btn-danger">Create new hero!</a>
            </div>
        </div>
    </header>
    <div class = "row">
        <div class="col-md-6">
            <h2>Detail Page</h2>
        </div>
        
    </div>
    

    <h2>Name: {{single_hero.name}}</h2>
    <h2>Alter Ego: {{single_hero.alter_ego}}</h2>
    <h2>Primary Ability: {{single_hero.primary_ability}}</h2>
    <h2>Secondary Ability: {{single_hero.secondary_ability}}</h2>
    <h2>Catchphrase: {{single_hero.catch_phrase}}</h2>
    <br>
    <a href="{% url 'superheroes:delete' single_hero.id %}" class = "btn btn-danger">Delete this hero</a>

    
</body>
</html>

superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'superheroes/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>

    <header>
        <div class = "row">
            <div class = "col-md-6">
                <h1>League of Superheroes</h1>
            </div>
            <div class = "col-md-6">
                <a href = "{% url 'superheroes:index' %}" class="btn btn-success" >Home</a>
                <a href="{% url 'superheroes:create' %}" class = "btn btn-danger">Create new hero!</a>
            </div>
        </div>
    </header>

    <h1>Editing hero: {{single_hero.name}}</h1>

    <form action="{% url 'superheroes:edit' single_hero.id %}" method = "post">
        {% csrf_token %}
        Name: <input type="text" name = "name" id = "name" value = "{{single_hero.name}}"><br>
        Alter Ego: <input type="text" name = "alter_ego" id = "alter_ego" value = "{{single_hero.alter_ego}}"><br>
        Primary Ability: <input type="text" name = "primary" id = "primary" value = "{{single_hero.primary_ability}}"><br>
        Secondary Ability: <input type="text" name = "secondary" id = "secondary" value = "{{single_hero.secondary_ability}}"><br>
        Catchphrase : <input type="text" name = "catchphrase" id = "catchphrase" value = "{{single_hero.catch_phrase}}"><br>
        <input type="submit" value = "Add!">
    </form>
</body>
</html>

superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'superheroes/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <header>
        <div class = "row">
            <div class = "col-md-6">
                <h1>League of Superheroes</h1>
            </div>
            <div class = "col-md-6">
                <a href = "{% url 'superheroes:index' %}" class="btn btn-success" >Home</a>
                <a href="{% url 'superheroes:create' %}" class = "btn btn-danger">Create new hero!</a>
            </div>
        </div>
    </header>
    <div class="row">
        <div class = "col-md-6">
            <h1>List of Heroes</h1>
        </div>
        
    </div>
    

    <ul>
        <div class="hero_list">
        {% for hero in all_heroes %}
           
                <div class="card"  style="width: 18rem;">
                    {% if hero.name == 'Spider-Man' %}
                        <img src = "{% static 'superheroes/Spiderman_picture.png' %}" alt="Picture of spiderman">
                        
                    {% elif hero.name == 'Batman' %}
                        <img src="{% static 'superheroes/Batman_picture.png' %}" class="card-img-top" alt="Picture of batman">
                    {% elif hero.name == 'Wonder Woman' %}   
                        <img src = "{% static 'superheroes/Wonderwoman_picture.png' %}" alt="Picture of Wonder Woman">
                    {% elif hero.name == 'Superman' %}
                        <img src = "{% static 'superheroes/Superman_picture.png' %}" alt="Picture of Superman">
                    {% endif %}
                    <div class="card-body">
                    <h5 class="card-title">{{hero.name}}</h5>
                    <a href="{% url 'superheroes:detail' hero.id %}" class="btn btn-primary">Details</a>
                    <a href="{% url 'superheroes:edit' hero.id %}" class="btn btn-primary">Edit</a>
                    </div>
                </div>
            </div>

        <!-- <li><h2>{{hero.name}}</h2><a href="{% url 'superheroes:detail' hero.id %}">Details</a><a href="{% url 'superheroes:edit' hero.id %}">Edit</a></li> -->
        {% endfor %}
    </ul>



    

</body>
</html>